### ISSUE TITLE
Failing Tests - error in Focus Search with discrete Params

### ISSUE THREAD

**Issue by danielhorn** [berndbischl/mlrMBO#108]
I tracked two of the failing tests down to this mlr or randomForest-error. It is, again, because we reduce the count of factor-levels of the discrete variable in the focus search. But this should be solved in mlr? Here is a short example with mlr:

library(mlr)
psa = makeParamSet(
  makeNumericParam("x1", lower = -2, upper = 1),
  makeDiscreteParam("x3", values = c("a", "b", "c"))
)
psb = makeParamSet(
  makeNumericParam("x1", lower = -2, upper = 1),
  makeDiscreteParam("x3", values = c("a", "b"))
)
da = cbind(generateDesign(10, psa), y = runif(10))
db = generateDesign(10, psb)
task = makeRegrTask(data = da, target = "y")
mod = train(learner = makeLearner("regr.randomForest"), task = task)
predict(mod, newdata = da)
predict(mod, newdata = db)

**Comment by jakob-r** [comment]
Is fixed. Was because of renaming in mlr
