### ISSUE TITLE
Multicrit plot is gone

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/mlrMBO#111]
Somehow the multicrit plot is gone. I have to remove the example run to todo-files so travis will work.
Can we bring the plot back to live?

**Comment by jakob-r** [comment]
I think it got lost here 7c413ccac3d86c8627ea810bd80acdd6ef365b39

**Comment by danielhorn** [comment]
Karin and I will work on this in the next weeks. I think, the complete code for the multicrit example run + plot has to be reviewed and partly rewritten.

**Comment by danielhorn** [comment]
We fixed this via 83e52daf42346ec894c68b17470d4db0cc69ce76, should be working again
