### ISSUE TITLE
exampleRuns: mean function should disable noisy?

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/mlrMBO#115]
Here we might should make sure that we dont replicate the calls of a mean and thus not noisy(?) function?
https://github.com/berndbischl/mlrMBO/blame/master/R/exampleRun.R#L122-L123
Or do I overlook something important?

**Comment by berndbischl** [comment]
I guess you are right. It seems in some cases we eval too often. Do you want to look at this and directly fix it?

**Comment by jakob-r** [comment]
I am working heavy on it now to make it multiFid-able. I just assigned @danielhorn to give me his opinion actually because he worked on it the most I guess.

**Comment by danielhorn** [comment]
I did not, I just made the multi crit functions. The single crit example run were @jakobbossek work.

But indeed, these 2 lines are from me, and, as Bernd, I guess you are right. If fun.mean is not NULL, noisy must be FALSE in the call of evaluate.

**Comment by jakob-r** [comment]
Ok - I have fixed it in my branch. Will merge soon
