### ISSUE TITLE
Multifid test broken - could not find function "addProperties"

### ISSUE THREAD

**Issue by danielhorn** [berndbischl/mlrMBO#118]
@jakob-r: I had to rename some stuff, since the learnerProperties in mlr changed. But I can not find an addLearnerProperties function ...

**Comment by jakob-r** [comment]
As mentioned in the NEWS we are not longer able to add learner properties like that. Only `mlr::RLearners` have the `$properties` slot, which you can directly manipulate - but you shouldn't. Instead for each specification of a `Learner` you can write a `getLearnerProperties.SpeicalLearnerClass` which than adds the needed property. This was necessary as some wrappers have properties depending on their state. This could also happen for normal Learners. 

I fixed it in this commit:
https://github.com/berndbischl/mlrMBO/commit/0f60f903fad201da7d7f4f816f7ba138461e588c
