### ISSUE TITLE
debug produces no output

### ISSUE THREAD

**Issue by zmjones** [berndbischl/mlrMBO#125]
I am not sure what is going on here and am having trouble debugging things as a result. Any help would be appreciated.

```{r}
library(mlrMBO)
library(smoof)
set.seed(1)
d = 2

fun = makeRosenbrockFunction(d)
ps = smoof::getParamSet(fun)

# ### GENERAL (init, iters, y.trafo)
ctrl = makeMBOControl(
  init.design.points = d*2,
  iters = d*2
)

### INFILL (crit, opt, interleave)
ctrl = setMBOControlInfill(ctrl,
  crit = "ei",
  opt = "focussearch",
  opt.focussearch.points = 5000L,
  opt.focussearch.maxit = 2L,
  opt.restarts = 2L,
  # FIXME: do we want to vary?
  interleave.random.points = 0
)
des = generateDesign(d*2, par.set = ps)

set.seed(1)

lrn = 
  makeLearner(id = "rf-infjackknife-calib", "regr.randomForest", predict.type = "se",
              ntree = 1000, keep.inbag = T, nodesize = 1L, se.method = "infjackknife", calibrate = FALSE)

debug(randomForestCI::randomForestInfJack)
debug(mlr:::infinitesimalJackknifeStandardError)
mbo.res = mbo(fun = fun, design = des, par.set = ps, learner = lrn, control = ctrl)
```
Produces output like:

```{r}
Browse[2]>
Browse[2]>
Browse[2]>
```

etc. I've tried this in Emacs and RStudio. The latter gives a warning that the debug location (it follows execution in the source pane) is only approximate because the source file is unavailable. The environment lists the correct objects as being there but I can't print anything. Loading the packages didn't seem to help. This problem does not occur when I debug `mlrMBO` functions.

**Comment by berndbischl** [comment]
there must be a browser or debug statement somewhere already in the code? have you checked for this?

**Comment by berndbischl** [comment]
ah wait. *you* debug in your example. sorry I misunderstood the problem. 

Can you maybe try to load the other packages via load_all? does that help?

**Comment by zmjones** [comment]
I tried loading `randomForestCI` and `mlr` via `library`. Do you mean replace `library` with `load_all`? From the docs the latter simulates the former.

**Comment by zmjones** [comment]
Attempting to do this with `mlr` after loading `mlrMBO` and `smoof`.

```{r}
Loading mlr
unloadNamespace("mlr") not successful. Forcing unload.
Error in importIntoEnv(pkgenv, exports, nsenv, exports) : 
  cannot change value of locked binding for 'test.min'
```

**Comment by berndbischl** [comment]
> Do you mean replace library with load_all? 

Yes. And I guess you have to do this in the right order.
So maybe load_all for smoof, mlr, then mlrMBO

**Comment by zmjones** [comment]
```{r}
> library(smoof)
Loading required package: ParamHelpers
Loading required package: BBmisc
Loading required package: checkmate
> devtools::load_all("~/Projects/mlr")
Loading mlr
Loading required package: ggplot2
> library(mlrMBO)
Loading required package: lhs
Error: package 'mlr' required by 'mlrMBO' could not be found
```

Using `library` to load `mlr` didn't throw this error but resulted in the same no-print debugging strangeness.
