### ISSUE TITLE
FIXME: configureMLR in evalTargetFun

### ISSUE THREAD

**Issue by danielhorn** [berndbischl/mlrMBO#64]
We should make this an issue:

  # FIXME: Do we need this here? This function is for function evaluation,
  # we should not need to configure mlr in this function.
  # BB: there is the problem if we call an mlr learner in the target function.....
  # BB: still, this is bad style here
  # DH: In this case - we could configure MLR before our model fit and
  # DH: restore the users old configuration after we are done?

**Comment by jakob-r** [comment]
So I guess it's closed
