### ISSUE TITLE
Inconsistent handling of performance measures

### ISSUE THREAD

**Issue by mllg** [berndbischl/mlrMBO#99]
I'm tuning a measure which needs to be maximized (0  [worst] <= cindex <= 1 [best]), so I've set `minimize = FALSE` in `makeMBOControl`. Depending on the object, I'm now getting sometimes negative performance measures (e.g. in TuneResult), sometimes positive ones (getOptPathY). This is highly confusing. Can we agree on something here?

**Comment by berndbischl** [comment]
another ping

**Comment by jakob-r** [comment]
@mllg What's the status?

**Comment by mllg** [comment]
This was a combination of mlr with mlrMBO which I cannot reproduce ATM. Closed until it pops up again.
